### ISSUE TITLE
Virtualenv-related exception after the latest update

### ISSUE THREAD

**Issue by azuk** [FreeCAD/FreeCAD-render#431] opened 2024-07-18 23:33 UTC
I updated Render workbench to the latest version and I now get an exception (see the log below) when starting FreeCAD. There was no exception before the update. The previous time I updated addons was probably 1-2 months ago so the "working" version would have been whatever was current back then.

```
[Render][Init] Checking dependencies...
[Render][Init] >>> Environment folder does not exist - Creating
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/tmpoz06dufb/virtualenv.pyz/__main__.py", line 163, in <module>
  File "/tmp/tmpoz06dufb/virtualenv.pyz/__main__.py", line 159, in run
  File "/tmp/tmpoz06dufb/virtualenv.pyz/virtualenv/__main__.py", line 18, in run
  File "/tmp/tmpoz06dufb/virtualenv.pyz/virtualenv/run/__init__.py", line 31, in cli_run
  File "/tmp/tmpoz06dufb/virtualenv.pyz/virtualenv/run/__init__.py", line 49, in session_via_cli
  File "/tmp/tmpoz06dufb/virtualenv.pyz/virtualenv/run/__init__.py", line 82, in build_parser
  File "/tmp/tmpoz06dufb/virtualenv.pyz/virtualenv/run/plugin/creators.py", line 24, in __init__
  File "/tmp/tmpoz06dufb/virtualenv.pyz/virtualenv/run/plugin/creators.py", line 31, in for_interpreter
  File "/tmp/tmpoz06dufb/virtualenv.pyz/virtualenv/run/plugin/base.py", line 45, in options
  File "/tmp/tmpoz06dufb/virtualenv.pyz/virtualenv/run/plugin/base.py", line 24, in entry_points_for
  File "/tmp/tmpoz06dufb/virtualenv.pyz/virtualenv/run/plugin/base.py", line 24, in <genexpr>
  File "/usr/lib/python3.8/importlib/metadata.py", line 79, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsFramework'
[Render][Init] Virtual environment error
```

FreeCAD version info:

```
OS: Ubuntu 20.04.6 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: almost the tip of FreeCAD-0-21 branch, see the hash
Build type: Debug
Branch: master
Hash: 4e49f9b26d9e0142e52472eedd6737cfcd2f6d86
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.3.0
Locale: English/United States (en_US)
Installed mods: 
  * 3DfindIT 1.2.0
  * woodworking 0.21.2.33771
  * Render 2024.7.4
  * BIM 2021.12.0
  * Reinforcement
  * Manipulator 1.5.7
  * Assembly4.backup1662941442.2770898
  * Assembly4 0.50.15
  * fasteners 0.5.24
  * Help 1.0.3
  * sheetmetal 0.4.23
  * Silk 0.1.5
  * dodo 1.0.1
  * Curves 0.6.42
```

**Comment by howetuft** [comment] 2024-07-19 04:30
Hello,

I think it's related to this issue:
https://stackoverflow.com/questions/72613928/module-virtualenv-create-via-global-ref-builtin-cpython-mac-os-has-no-attribut

The `virtualenv` package which is installed on your system must be corrupted (it looks like a version for MacOS on Arm arch!!!), probably due to a previous wrong installation.

The post suggests you uninstall and reinstall the package:
`pip uninstall virtualenv && sudo pip uninstall virtualenv`
(the reinstall can be done by Render, go to Preferences and clikc on "Reset Plugins Environment")
You may have to do it several times, according to the post. Let me know!

**Comment by azuk** [comment] 2024-07-20 01:03
I did some digging and the problem is that `virtualenv.pyz` (the one downloaded by Render WB code) calls `entry_points()` from `importlib.metadata` and the result includes entry points from `entry_points.txt` of system's virtualenv (`/usr/lib/python3/dist-packages/virtualenv-20.0.17.egg-info/entry_points.txt` from package `python3-virtualenv`).

There is no corruption, those entry points are valid for system's virtualenv, but they are different from entry points of virtualenv.pyz --- for example, as indicated by the logged errors, virtualenv.pyz's create/via_global_ref/builtin/cpython/mac_os.py doesn't contain `CPython2macOsFramework` but the same file of system's virtualenv contains that class, simply because it is a different version of virtualenv.

It seems to me that if you want to use a specific version of a package that might already be installed in the system, there should be an isolated environment in which you do that. Unfortunately in this case the package that needs isolation is the package that is used to create such environments :)

I'm not really a python programmer so I don't know if this case is known to virtualenv authors/users and what would be the proper way to solve it.

**Comment by howetuft** [comment] 2024-07-20 02:46
But it seems to me that your system `virtualenv` version should be 20.25.0 (https://packages.ubuntu.com/noble/python3-virtualenv), not 20.0.17 as visible above.
Could you please try to install/update the package to your distro standard version (`sudo apt install python3-virtualenv`)?

**Comment by azuk** [comment] 2024-07-20 03:18
I'm using (K)Ubuntu 20.04, whose codename is focal, so the correct link for my system would be https://packages.ubuntu.com/focal/python3-virtualenv. Noble is 24.04. I have the distro standard version already.

**Comment by howetuft** [comment] 2024-07-20 04:27
OK, my bad. Maybe a solution would be to rely on system virtualenv when it exists. I'm gonna see what I can do.

**Comment by howetuft** [comment] 2024-07-20 06:01
I've introduced a setting to optionally rely on local virtualenv package (in Preferences). It's in `dev` branch (6145c8c7a08f5f05c2ef921379dd413d8d00d58b): could you please test whether it fixes your problem?

**Comment by azuk** [comment] 2024-07-21 01:57
I tested the `dev` branch version and it does indeed solve this problem if I enable the new setting. Thanks.

However, there are now problems with Qt6 related libraries:

```
[Render][Init] Checking dependencies...
[Render][Init] >>> Environment folder does not exist - Creating
[Render][Init] Checking package 'renderplugin' - OK
[Render][Init] Checking package 'PyQt6-WebEngine' - ERROR (return code: 1)
[Render][Init] Checking package 'QtPy' - OK
[Render][Init] Checking package 'PyQt6' - ERROR (return code: 1)
[Render][Init] WARNING - The following dependencies could not be installed:'PyQt6-WebEngine', 'PyQt6'
[Render][Init] You may try to install those packages on your own with the following command-line statement:
"/home/foo/.local/share/FreeCAD/.rendervenv/bin/python" -u -m pip install --prefer-binary --require-virtualenv 'PyQt6-WebEngine', 'PyQt6'
[Render][Init] Render virtual environment: 2 error(s)
[Render][Init] Done.
```

And when attempting to install those libraries manually:

```
[prompt] /home/foo/.local/share/FreeCAD/.rendervenv/bin/python -u -m pip install --prefer-binary --require-virtualenv 'PyQt6-WebEngine' 'PyQt6'
Collecting PyQt6-WebEngine
  Using cached PyQt6_WebEngine-6.3.1-cp37-abi3-manylinux1_x86_64.whl (242 kB)
Collecting PyQt6
  Using cached PyQt6-6.3.1-cp37-abi3-manylinux1_x86_64.whl (7.8 MB)
Collecting PyQt6-sip<14,>=13.4
  Using cached PyQt6_sip-13.8.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (282 kB)
ERROR: Could not find a version that satisfies the requirement PyQt6-WebEngine-Qt6>=6.3.0 (from PyQt6-WebEngine) (from versions: none)
ERROR: No matching distribution found for PyQt6-WebEngine-Qt6>=6.3.0 (from PyQt6-WebEngine)
```

I suppose I should upgrade to 22.04 (and possibly all the way to 24.04 once 24.04.1is released).

**Comment by howetuft** [comment] 2024-07-21 04:22
Wait a minute: there is something weird in this line:
 `Using cached PyQt6_WebEngine-6.3.1-cp37-abi3-manylinux1_x86_64.whl (242 kB)`
Why is it using a version 3.7 of Python???

Could you please enter the following in Python console:
`import Render; Render.utils.find_python()`
and, with the result, in a shell:
`<path/to/python> --version`

**Comment by azuk** [comment] 2024-07-21 16:36
`import Render; Render.utils.find_python()` gives me `'/usr/bin/python3'` and `/usr/bin/python3 --version` gives me `Python 3.8.10`, which is the only installed 3-series python on this machine (there is 2 series `2.7.18` as well).

`/home/foo/.local/share/FreeCAD/.rendervenv/bin/python` is a symlink to `/home/foo/.local/share/FreeCAD/.rendervenv/bin/python3` which is a symlink to `/usr/bin/python3`. 

All renderenv Python libraries are under `/home/foo/.local/share/FreeCAD/.rendervenv/lib/python3.8/site-packages` directory and all pyc files are `*.cpython-38.pyc`.

So, I don't see anything related to 3.7 version anywhere. I wonder where that cp37 comes from.

**Comment by howetuft** [comment] 2024-07-21 16:47
Hello,

pip cache maintenance is documented here:
https://pip.pypa.io/en/stable/topics/caching/

If your patience has not run out, can you please try any recipe from there (install without cache, remove offending wheel from cache etc.)?
It would be a pity to have to upgrade your entire system just to use a Render feature...

**Comment by azuk** [comment] 2024-07-21 19:50
I tried with `--no-cache-dir` and after manually removing the cache directory entirely (Ubuntu 20.04's pip (20.0.2) doesn't support cache management subcommands) and it didn't make any difference.

It seems that pip 20.0.2 doesn't support those "manylinux wheels" used for PyQt6 packages. https://github.com/pypa/manylinux suggests that in case of `manylinux_x_y` tag (`manylinux_2_28` is used by these packages) pip >= 20.3 is needed.

Indeed, if I install the latest pip in user install directory (`~/.local`) and use that to try to install the PyQt6-WebEngine and PyQt6, they and their dependencies are installed without problems.

As for virtual environments, some people (https://stackoverflow.com/questions/51720909/how-to-get-python-m-venv-to-directly-install-latest-pip-version) suggest that it would be best to create a virtual environment without pip (--without-pip) and separately install the latest pip in that environment using ensurepip or something. I couldn't get that to work, but the other suggestion of simply upgrading pip after creating the virtual environment did work and after that I could install the PyQt6 packages inside my test virtual environment.

**Comment by howetuft** [comment] 2024-07-21 20:28
> after that I could install the PyQt6 packages inside my test virtual environment.

Good news! So the root cause is clear now.
For Render, now: go to Render preferences, you'll find a parameter named `Update Pip when reloading`: check it.
Then, back to the Python console, enter:
`import Render; Render.reload()`
This should update pip and, hopefully, pull the right versions of the packages in Render virtual env...

**Comment by howetuft** [comment] 2024-07-26 13:31
Hello,
Are you satisfied with the last posts, can I close the issue?

**Closed** 2024-08-04 08:23 UTC
