### ISSUE TITLE
Problems with "glass" properties in Pbrt v4

### ISSUE THREAD

**Issue by claudiomush** [FreeCAD/FreeCAD-render#163] opened 2022-01-11 13:52 UTC
Hello, I've some problem with the glass assigned to a part. 
Is there a way to link a "local" setting to a "passthrough" set for pbrt?
Even if glass keeps a 100% of transp my result is opaque.
Regards

**Comment by howetuft** [comment] 2022-01-11 17:15
Hello,
Could you please post your FreeCAD project, so that I can reproduce? Thanks!

**Comment by claudiomush** [comment] 2022-01-12 07:30
Hello, with the new version of render I see something changed about the power of area lights. Now it needs to reduce a factor 100 (!) to obtain the some effect than before. Have you any feedback of that?
Regards

[as4_molla_scaric3.zip](https://github.com/FreeCAD/FreeCAD-render/files/7852523/as4_molla_scaric3.zip)

**Comment by howetuft** [comment] 2022-01-12 14:16
About area lights power: Yes, I had to rework them. Indeed, I harmonized the different units used in the code, in order to export to the renders in standard and similar units from one renderer to another (meters, watts...). This implied a work of harmonization of the units, including the power units. For pbrt, this translates well into a factor of 100, as shown in the following commit: 31f368371863bdc6018111f40555e928c7e871b4

Thanks for your file, I will try to look at it in the next days...

**Comment by claudiomush** [comment] 2022-01-12 14:27
Clear now, many thanks.

**Comment by claudiomush** [comment] 2022-01-12 14:36
If I remember correctly you were working on a new material tool, a huge task. May I help in any way ? Searching data, testing something... I'm afraid, my python is basic.

**Comment by howetuft** [comment] 2022-01-12 18:51
Yes, I had a plan to create a library of rendering materials... and it's actually created, although it's modestly only 9 materials at this point. However, I think they do allow for the most common renders: plastics, metals, carpaint...
To create more materials though, I will need to add an advanced feature, which is Texture management. It's a new and heavy development I'm planning for 2022.
Your help can be welcome, there is not only Python code to do: your testing and feedback is much valuable.
Also, if you feel like writing documentation, don't hesitate!

**Comment by claudiomush** [comment] 2022-01-13 08:44
I applied last update of render wb and assembly4 and executing "render" command on your file I get a funny result in attachment: it's the rendering resulting png. 
In addition even assigned the proper material to the body of my original file the aspect remains opaque.
Something fails somewhere. About some help I'll try to do what in my capabilties.
![Screenshot at 2022-01-13 09-40-15](https://user-images.githubusercontent.com/83174729/149295824-3ddda3c1-095a-4e35-a994-0fcdca054666.png)

**Comment by howetuft** [comment] 2022-01-13 16:32
Argh! They silently removed the "tint" parameter of glass (Dielectric) material, see https://github.com/mmp/pbrt-v4/issues/182. I run an older version of pbrt than yours, so I didn't notice.
I'll have a look at that in the next few days.
(Again, it shows pbrt is just an illustration for a book, not a general purpose renderer...)

**Comment by claudiomush** [comment] 2022-01-14 08:37
I see, pity. I'm not chained to pbrt but last two years I tried to compile appleseed (which has no updates from long time) and luxcore which depends from Intel peculiar libraries, both unsuccessfully. Please suggest me a real alternative linux compatible if available. Regards

**Comment by claudiomush** [comment] 2022-01-14 10:33
Just to try something different I easily compiled the following libraries:
https://tsubo164.github.io/Fujiyama-Docs/index.html
http://www.horde3d.org/home.html
https://www.cycles-renderer.org/
I'd like your comments about.
Regards

**Comment by howetuft** [comment] 2022-01-14 10:54
Cycles (standalone) is supported! It's usually a nightmare to compile, but if you succeeded, it's an excellent choice.
The others I don't know.
By the way, what distro do you use?

**Comment by claudiomush** [comment] 2022-01-14 11:45
I compiled cycles in while, luxcore is an endless nightmare! Anyway please have a look to the screenshots, from cycles, in attachment: it seems to me an unusual behavior with that small windows in addition and a strange "ballet" of canvas output.
![Screenshot at 2022-01-14 12-38-30](https://user-images.githubusercontent.com/83174729/149510134-f09fb477-484b-476c-9445-a5f64e3c52ef.png)
![Screenshot at 2022-01-14 12-38-15](https://user-images.githubusercontent.com/83174729/149510150-04964294-3817-4eaa-8e04-c2bea9693bdf.png)
As distro I'm using Ubuntu Mate 20.04.

**Comment by howetuft** [comment] 2022-01-14 13:16
Anyway, very nice renderings!

**Comment by claudiomush** [comment] 2022-01-14 14:07
Thanks. Be patient but of course was generated a new window a rendering but with the new render wb appears also a new win red marked. This is new and uncontrolled until rendering tab was erased. Is this correct?
![Screenshot at 2022-01-14 12-38-30](https://user-images.githubusercontent.com/83174729/149527866-c99fb0b9-1e2e-4ad9-8388-9e3c3617b3ad.png)
Ah, cycles is a flash but not so accurate as pbrt; I'll try to more accurate test with different materials/lights, etc.
If I would try to add some material where have I to start for?

**Comment by claudiomush** [comment] 2022-01-14 14:34
I believe there was a problem. Do you remember my big assembly as first try on pbrt? Using cycles it doesn't recognizes area lights and the rendering canvas, done a render and leave it, is populated of the buffer/win of the assy components but not selectable. I'm afraid of but it's new for me.
![Screenshot at 2022-01-14 15-24-09](https://user-images.githubusercontent.com/83174729/149532422-866e6c8a-770d-4c57-b636-5dd8afa495a0.png)
![Screenshot at 2022-01-14 15-28-25](https://user-images.githubusercontent.com/83174729/149532449-226b4a77-ee14-4169-91b9-1fb6888b0d28.png)

**Comment by howetuft** [comment] 2022-01-15 08:14
> with the new render wb appears also a new win red marked.
You get a new window each time you execute a rendering. In your screenshot, you must have run 2 renderings, so you get 2 windows, as stated in the tabs below (look for "rendering result"). It just appears that one is maximized (the one that displays the full picture), the other is minimized (the one you marked in red). To me, there is no malfunction. However, I may add an action to menu in order to control maximization/minimization.
Please note it's an old feature, I just recently enhanced the image display widget in it (see the context menu, for instance, or the scrollbars in minimized window)
> the rendering canvas, done a render and leave it, is populated of the buffer/win of the assy components but not selectable
It's because the "Rendering result" window is on top of all the other windows and maximized, so logically it does not allow you to interact with other windows through itself. But you can see the other windows through "Rendering result" as its background is transparent: maybe a bit frustrating, I understand.
Hence 2 remarks:
- You can still switch to other windows using tabs bar, underneath. Or you can reorganize your windows using "Tile" in FreeCAD "Windows" menu.
- Background transparency for "Rendering result" window is misleading and undesirable, so I must work on it. Just a question however, to help me: did you specifically ask for window background transparency, somewhere in settings?

> If I would try to add some material where have I to start for?
I'm not sure to understand: where do you want to add materials? In your model, or in Render materials library?

> Using cycles it doesn't recognizes area lights
Well, it should! Can you please increase the power of your area lights? Try very high values, and just let me know if they are still invisible... Thanks!

> cycles is a flash but not so accurate as pbrt
I think we're going to start a renderer war :smile:

**Comment by howetuft** [comment] 2022-01-15 12:50
In addition, please note I removed 'tint' parameter from glass material for Pbrt (b831038bd85bc9368bec035e1b064232ae6c7184)

**Comment by howetuft** [comment] 2022-01-15 21:31
Update:
I understood what was wrong with the windows: it was related to the style sheet. I made a fix (https://github.com/FreeCAD/FreeCAD-render/pull/166). Can you tell me if it works correctly from your point of view?
My other questions (area lights, materials) still open: do not hesitate to bring me feedback!

**Comment by claudiomush** [comment] 2022-01-16 11:49
Great touch. Fix #166 rewind the tape and now the background is clean, for my preference. Below a screenshot before fixing:
![Screenshot at 2022-01-16 11-57-33](https://user-images.githubusercontent.com/83174729/149658144-c0f0f097-8710-45cf-9a55-9f8854620f22.png)
and after fixing:
![Screenshot at 2022-01-16 12-09-19](https://user-images.githubusercontent.com/83174729/149658154-657a9672-7cca-4b64-acfb-df3b90a4b8b1.png)
Your suspect were right about arealights in cycles: for a sensitive results it needs a power of 6000.0, used for previous shot.
At the same power, below the shot from pbrt, that now without "tint" runs:
![Screenshot at 2022-01-16 12-23-41](https://user-images.githubusercontent.com/83174729/149658292-6511360d-f09d-41be-b0d8-cee5ebb4c01d.png)
and finally a shot from pbrt area power of 6.0:
![Screenshot at 2022-01-16 12-29-47](https://user-images.githubusercontent.com/83174729/149658314-c198a670-0ce7-4672-b77b-293241bfeeea.png)
even too much!
Many thanks, the model attached.
[Mount.zip](https://github.com/FreeCAD/FreeCAD-render/files/7876875/Mount.zip)

**Comment by claudiomush** [comment] 2022-01-16 11:52
Forgotten, sorry: about adding material I was thinking to Render material library if impossible to keeps a "local' lib.

**Comment by howetuft** [comment] 2022-01-16 15:46
Lights powers balancing between renderers is really a hassle, I'm at a loss with that: it's very hard to get the same result between all engines. I introduced magic numbers into the code, but it appears not really efficient. Perhaps one day, I'll add some user coefficients in projects parameters... 
For materials, your help will be welcome but, beforehand, I have to add some support for textures. It will take a few weeks I think...

**Comment by howetuft** [comment] 2022-01-17 14:42
If you don't mind, I may close this issue at this stage (please reopen if you consider there is a need).

**Closed by howetuft** 2022-01-17 14:42 UTC
