### ISSUE TITLE
Cycles Adding smooth to curved objects 

### ISSUE THREAD

**Issue by MisterMakerNL** [FreeCAD/FreeCAD-render#142] opened 2021-04-05 20:41 UTC
Something that would greatly improve render qualities in cycles is adding smooth to some objects.
IT would be interesting to do this manually of think of a way to do this automatically.
As far as I understand it can be done by adding this string to the mesh: 
`<state interpolation="smooth">`
Got it from this topic:
https://lists.blender.org/pipermail/bf-cycles/2019-February/003413.html
did some testing with this:
No smooth diffuse:
![afbeelding](https://user-images.githubusercontent.com/29804962/113775663-5cb8cb80-9729-11eb-9af6-8923687a1410.png)
With smooth diffuse:
![afbeelding](https://user-images.githubusercontent.com/29804962/113775752-7528e600-9729-11eb-89d5-afb9874dda00.png)
Smooth glossy:
![afbeelding](https://user-images.githubusercontent.com/29804962/113776136-dcdf3100-9729-11eb-8913-696242c19eff.png)
No smooth glossy:
![afbeelding](https://user-images.githubusercontent.com/29804962/113776186-ebc5e380-9729-11eb-9592-5d06fe6193a2.png)
If I see this in CAd renders, I think it should be on by default and maybe add an option to disable it.
current test code:
` <shader name="Sphere">
        <glossy_bsdf name="Sphere_bsdf" color="0.800000011920929, 0.800000011920929, 0.800000011920929"/>
        <connect from="Sphere_bsdf bsdf" to="output surface"/>
    </shader>
    <state interpolation="smooth" shader="Sphere">
        <mesh P="1.2820419073104858 0.1762126088142395 -4.829628944396973  1.2940952777862549 -3.1696192585426613e-16 -4.829628944396973  3.0616169991140216e-16 -7.498798786105971e-32 -5.0  2.5 -6.123233998228043e-16 -4.330127239227295  1.1869587898254395 0.5155689716339111 -4.829628944396973  1.0038442611694336 0.8166878819465637 -4.829628944396973  0.746279239654541 1.0572367906570435 -4.829628944396973  2.4072933197021484 0.6744919419288635 -4.330127239227295  0.4333661198616028 1.2193753719329834 -4.829628944396973  2.1360485553741455 1.2989598512649536 -4.330127239227295  0.08831217885017395 1.2910784482955933 -4.829628944396973  1.7063828706741333 1.8270899057388306 -4.330127239227295  3.502603769302368 0.4814217984676361 -3.535533905029297  3.535533905029297 -8.659560338728758e-16 -3.535533905029297  4.330127239227295 -1.0605752472130298e-15 -2.5  -0.26329144835472107 1.2670280933380127 -4.829628944396973  1.1501625776290894 2.219712972640991 -4.330127239227295  3.2428317070007324 1.4085605144500732 -3.535533905029297  -0.595367968082428 1.14900803565979 -4.829628944396973  0.5086400508880615 2.4477102756500244 -4.330127239227295  2.742553472518921 2.2312328815460205 -3.535533905029297  -0.8832887411117554 0.945771336555481 -4.829628944396973  -0.17060603201389313 2.4941718578338623 -4.330127239227295  2.038872718811035 2.888424873352051 -3.535533905029297  -1.1057000160217285 0.6723911166191101 -4.829628944396973  4.169554233551025 1.1682542562484741 -2.5  -0.8371990323066711 2.355652332305908 -4.330127239227295  1.1839781999588013 3.331395387649536 -3.535533905029297  -1.2461066246032715 0.3491427004337311 -4.829628944396973  3.699744462966919 2.2498645782470703 -2.5  -1.44170081615448 2.0424246788024902 -4.330127239227295  0.24127337336540222 3.527291774749756 -3.535533905029297  -1.2940952777862549 1.3078684219880541e-15 -4.829628944396973  2.9555418491363525 3.1646125316619873 -2.5  -1.939278244972229 1.577719807624817 -4.330127239227295  4.7846455574035645 0.657634437084198 -1.2940952777862549  4.829628944396973 -1.1829179332573624e-15 -1.2940952777862549  5.0 -1.2246467996456087e-15 -1.0106431208405098e-14  -0.7193256616592407 3.46158504486084 -3.535533905029297  -1.2461066246032715 -0.3491427004337311 -4.829628944396973  1.9921400547027588 3.844655752182007 -2.5  -2.2930283546447754 0.996002733707428 -4.330127239227295  4.429790496826172 1.9241294860839844 -1.2940952777862549  -1.6265755891799927 3.139148235321045 -3.535533905029297  -1.1057000160217285 -0.6723911166191101 -4.829628944396973  0.8809903860092163 4.239558696746826 -2.5  -2.476714849472046 0.3404166102409363 -4.330127239227295  3.7463977336883545 3.0479207038879395 -1.2940952777862549  -2.4131898880004883 2.583895444869995 -3.535533905029297  -0.8832887411117554 -0.945771336555481 -4.829628944396973  -0.2954983115196228 4.320032596588135 -2.5  -2.476714849472046 -0.3404166102409363 -4.330127239227295  2.7851521968841553 3.9456615447998047 -1.2940952777862549  -3.0208287239074707 1.837006688117981 -3.535533905029297  4.814586639404297 1.348983883857727 -1.6653345369377348e-15  -0.595367968082428 -1.14900803565979 -4.829628944396973  -1.4500712156295776 4.080109596252441 -2.5  -2.2930283546447754 -0.996002733707428 -4.330127239227295  1.6173443794250488 4.5507707595825195 -1.2940952777862549  -3.4044268131256104 0.9538756608963013 -3.535533905029297  4.272097110748291 2.5979197025299072 -1.6653345369377348e-15  -0.26329144835472107 -1.2670280933380127 -4.829628944396973  -2.4970991611480713 3.537583351135254 -2.5  -1.939278244972229 -1.577719807624817 -4.330127239227295  0.32958555221557617 4.818370342254639 -1.2940952777862549  -3.535533905029297 3.573162748213114e-15 -3.535533905029297  3.4127657413482666 3.654179811477661 -1.6653345369377348e-15  0.08831217885017395 -1.2910784482955933 -4.829628944396973  -3.3589284420013428 2.7326910495758057 -2.5  4.7846455574035645 0.657634437084198 1.2940952777862549  4.829628944396973 -1.1829179332573624e-15 1.2940952777862549  4.330127239227295 -1.0605752472130298e-15 2.5  -1.44170081615448 -2.0424246788024902 -4.330127239227295  -0.9826170802116394 4.728612899780273 -1.2940952777862549  -3.4044268131256104 -0.9538756608963013 -3.535533905029297  2.3003251552581787 4.439425945281982 -1.6653345369377348e-15  0.4333661198616028 -1.2193753719329834 -4.829628944396973  -3.9716415405273438 1.7251273393630981 -2.5  4.429790496826172 1.9241294860839844 1.2940952777862549  -0.8371990323066711 -2.355652332305908 -4.330127239227295  -2.2219436168670654 4.288156509399414 -1.2940952777862549  -3.0208287239074707 -1.837006688117981 -3.535533905029297  1.017280101776123 4.895420551300049 -1.6653345369377348e-15  0.746279239654541 -1.0572367906570435 -4.829628944396973  -4.289795875549316 0.5896188616752625 -2.5  3.7463977336883545 3.0479207038879395 1.2940952777862549  -0.17060603201389313 -2.4941718578338623 -4.330127239227295  -3.296478509902954 3.5296666622161865 -1.2940952777862549  -2.4131898880004883 -2.583895444869995 -3.535533905029297  -0.34121206402778625 4.988343715667725 -1.6653345369377348e-15  1.0038442611694336 -0.8166878819465637 -4.829628944396973  -4.289795875549316 -0.5896188616752625 -2.5  2.7851521968841553 3.9456615447998047 1.2940952777862549  0.5086400508880615 -2.4477102756500244 -4.330127239227295  -4.126528739929199 2.5093977451324463 -1.2940952777862549  4.169554233551025 1.1682542562484741 2.5  -1.6265755891799927 -3.139148235321045 -3.535533905029297  -1.6743980646133423 4.711304664611816 -1.6653345369377348e-15  1.1869587898254395 -0.5155689716339111 -4.829628944396973  -3.9716415405273438 -1.7251273393630981 -2.5  1.6173443794250488 4.5507707595825195 1.2940952777862549  1.1501625776290894 -2.219712972640991 -4.330127239227295  -4.650533199310303 1.30301833152771 -1.2940952777862549  3.699744462966919 2.2498645782470703 2.5  -0.7193256616592407 -3.46158504486084 -3.535533905029297  -2.88340163230896 4.0848493576049805 -1.6653345369377348e-15  1.2820419073104858 -0.1762126088142395 -4.829628944396973  -3.3589284420013428 -2.7326910495758057 -2.5  0.32958555221557617 4.818370342254639 1.2940952777862549  1.7063828706741333 -1.8270899057388306 -4.330127239227295  -4.829628944396973 4.881031170201168e-15 -1.2940952777862549  2.9555418491363525 3.1646125316619873 2.5  0.24127337336540222 -3.527291774749756 -3.535533905029297  -3.878556489944458 3.155439615249634 -1.6653345369377348e-15  3.502603769302368 0.4814217984676361 3.535533905029297  3.535533905029297 -8.659560338728758e-16 3.535533905029297  2.5 -6.123233998228043e-16 4.330127239227295  -2.4970991611480713 -3.537583351135254 -2.5  -0.9826170802116394 4.728612899780273 1.2940952777862549  2.1360485553741455 -1.2989598512649536 -4.330127239227295  -4.650533199310303 -1.30301833152771 -1.2940952777862549  1.9921400547027588 3.844655752182007 2.5  1.1839781999588013 -3.331395387649536 -3.535533905029297  -4.586056709289551 1.992005467414856 -1.6653345369377348e-15  3.2428317070007324 1.4085605144500732 3.535533905029297  -1.4500712156295776 -4.080109596252441 -2.5  -2.2219436168670654 4.288156509399414 1.2940952777862549  2.4072933197021484 -0.6744919419288635 -4.330127239227295  -4.126528739929199 -2.5093977451324463 -1.2940952777862549  0.8809903860092163 4.239558696746826 2.5  2.038872718811035 -2.888424873352051 -3.535533905029297  -4.953429698944092 0.6808332204818726 -1.6653345369377348e-15  2.742553472518921 2.2312328815460205 3.535533905029297  -0.2954983115196228 -4.320032596588135 -2.5  -3.296478509902954 3.5296666622161865 1.2940952777862549  -3.296478509902954 -3.5296666622161865 -1.2940952777862549  -0.2954983115196228 4.320032596588135 2.5  2.742553472518921 -2.2312328815460205 -3.535533905029297  -4.953429698944092 -0.6808332204818726 -1.6653345369377348e-15  2.038872718811035 2.888424873352051 3.535533905029297  0.8809903860092163 -4.239558696746826 -2.5  -4.126528739929199 2.5093977451324463 1.2940952777862549  2.4072933197021484 0.6744919419288635 4.330127239227295  -2.2219436168670654 -4.288156509399414 -1.2940952777862549  -1.4500712156295776 4.080109596252441 2.5  3.2428317070007324 -1.4085605144500732 -3.535533905029297  -4.586056709289551 -1.992005467414856 -1.6653345369377348e-15  1.1839781999588013 3.331395387649536 3.535533905029297  1.9921400547027588 -3.844655752182007 -2.5  -4.650533199310303 1.30301833152771 1.2940952777862549  2.1360485553741455 1.2989598512649536 4.330127239227295  -0.9826170802116394 -4.728612899780273 -1.2940952777862549  -2.4970991611480713 3.537583351135254 2.5  3.502603769302368 -0.4814217984676361 -3.535533905029297  -3.878556489944458 -3.155439615249634 -1.6653345369377348e-15  0.24127337336540222 3.527291774749756 3.535533905029297  2.9555418491363525 -3.1646125316619873 -2.5  -4.829628944396973 4.881031170201168e-15 1.2940952777862549  1.7063828706741333 1.8270899057388306 4.330127239227295  0.32958555221557617 -4.818370342254639 -1.2940952777862549  -3.3589284420013428 2.7326910495758057 2.5  1.2820419073104858 0.1762126088142395 4.829628944396973  1.2940952777862549 -3.1696192585426613e-16 4.829628944396973  3.0616169991140216e-16 -7.498798786105971e-32 5.0  -2.88340163230896 -4.0848493576049805 -1.6653345369377348e-15  -0.7193256616592407 3.46158504486084 3.535533905029297  3.699744462966919 -2.2498645782470703 -2.5  -4.650533199310303 -1.30301833152771 1.2940952777862549  1.1501625776290894 2.219712972640991 4.330127239227295  1.6173443794250488 -4.5507707595825195 -1.2940952777862549  -3.9716415405273438 1.7251273393630981 2.5  1.1869587898254395 0.5155689716339111 4.829628944396973  -1.6743980646133423 -4.711304664611816 -1.6653345369377348e-15  -1.6265755891799927 3.139148235321045 3.535533905029297  4.169554233551025 -1.1682542562484741 -2.5  -4.126528739929199 -2.5093977451324463 1.2940952777862549  0.5086400508880615 2.4477102756500244 4.330127239227295  2.7851521968841553 -3.9456615447998047 -1.2940952777862549  -4.289795875549316 0.5896188616752625 2.5  1.0038442611694336 0.8166878819465637 4.829628944396973  -0.34121206402778625 -4.988343715667725 -1.6653345369377348e-15  -2.4131898880004883 2.583895444869995 3.535533905029297  -3.296478509902954 -3.5296666622161865 1.2940952777862549  -0.17060603201389313 2.4941718578338623 4.330127239227295  3.7463977336883545 -3.0479207038879395 -1.2940952777862549  -4.289795875549316 -0.5896188616752625 2.5  0.746279239654541 1.0572367906570435 4.829628944396973  1.017280101776123 -4.895420551300049 -1.6653345369377348e-15  -3.0208287239074707 1.837006688117981 3.535533905029297  -2.2219436168670654 -4.288156509399414 1.2940952777862549  -0.8371990323066711 2.355652332305908 4.330127239227295  4.429790496826172 -1.9241294860839844 -1.2940952777862549  -3.9716415405273438 -1.7251273393630981 2.5  0.4333661198616028 1.2193753719329834 4.829628944396973  2.3003251552581787 -4.439425945281982 -1.6653345369377348e-15  -3.4044268131256104 0.9538756608963013 3.535533905029297  -0.9826170802116394 -4.728612899780273 1.2940952777862549  -1.44170081615448 2.0424246788024902 4.330127239227295  4.7846455574035645 -0.657634437084198 -1.2940952777862549  -3.3589284420013428 -2.7326910495758057 2.5  0.08831217885017395 1.2910784482955933 4.829628944396973  3.4127657413482666 -3.654179811477661 -1.6653345369377348e-15  -3.535533905029297 3.573162748213114e-15 3.535533905029297  0.32958555221557617 -4.818370342254639 1.2940952777862549  -1.939278244972229 1.577719807624817 4.330127239227295  -2.4970991611480713 -3.537583351135254 2.5  -0.26329144835472107 1.2670280933380127 4.829628944396973  4.272097110748291 -2.5979197025299072 -1.6653345369377348e-15  -3.4044268131256104 -0.9538756608963013 3.535533905029297  1.6173443794250488 -4.5507707595825195 1.2940952777862549  -2.2930283546447754 0.996002733707428 4.330127239227295  -1.4500712156295776 -4.080109596252441 2.5  -0.595367968082428 1.14900803565979 4.829628944396973  4.814586639404297 -1.348983883857727 -1.6653345369377348e-15  -3.0208287239074707 -1.837006688117981 3.535533905029297  2.7851521968841553 -3.9456615447998047 1.2940952777862549  -2.476714849472046 0.3404166102409363 4.330127239227295  -0.2954983115196228 -4.320032596588135 2.5  -0.8832887411117554 0.945771336555481 4.829628944396973  -2.4131898880004883 -2.583895444869995 3.535533905029297  3.7463977336883545 -3.0479207038879395 1.2940952777862549  -2.476714849472046 -0.3404166102409363 4.330127239227295  0.8809903860092163 -4.239558696746826 2.5  -1.1057000160217285 0.6723911166191101 4.829628944396973  -1.6265755891799927 -3.139148235321045 3.535533905029297  4.429790496826172 -1.9241294860839844 1.2940952777862549  -2.2930283546447754 -0.996002733707428 4.330127239227295  1.9921400547027588 -3.844655752182007 2.5  -1.2461066246032715 0.3491427004337311 4.829628944396973  -0.7193256616592407 -3.46158504486084 3.535533905029297  4.7846455574035645 -0.657634437084198 1.2940952777862549  -1.939278244972229 -1.577719807624817 4.330127239227295  2.9555418491363525 -3.1646125316619873 2.5  -1.2940952777862549 1.3078684219880541e-15 4.829628944396973  0.24127337336540222 -3.527291774749756 3.535533905029297  -1.44170081615448 -2.0424246788024902 4.330127239227295  3.699744462966919 -2.2498645782470703 2.5  -1.2461066246032715 -0.3491427004337311 4.829628944396973  1.1839781999588013 -3.331395387649536 3.535533905029297  -0.8371990323066711 -2.355652332305908 4.330127239227295  4.169554233551025 -1.1682542562484741 2.5  -1.1057000160217285 -0.6723911166191101 4.829628944396973  2.038872718811035 -2.888424873352051 3.535533905029297  -0.17060603201389313 -2.4941718578338623 4.330127239227295  -0.8832887411117554 -0.945771336555481 4.829628944396973  2.742553472518921 -2.2312328815460205 3.535533905029297  0.5086400508880615 -2.4477102756500244 4.330127239227295  -0.595367968082428 -1.14900803565979 4.829628944396973  3.2428317070007324 -1.4085605144500732 3.535533905029297  1.1501625776290894 -2.219712972640991 4.330127239227295  -0.26329144835472107 -1.2670280933380127 4.829628944396973  3.502603769302368 -0.4814217984676361 3.535533905029297  1.7063828706741333 -1.8270899057388306 4.330127239227295  0.08831217885017395 -1.2910784482955933 4.829628944396973  2.1360485553741455 -1.2989598512649536 4.330127239227295  0.4333661198616028 -1.2193753719329834 4.829628944396973  2.4072933197021484 -0.6744919419288635 4.330127239227295  0.746279239654541 -1.0572367906570435 4.829628944396973  1.0038442611694336 -0.8166878819465637 4.829628944396973  1.1869587898254395 -0.5155689716339111 4.829628944396973  1.2820419073104858 -0.1762126088142395 4.829628944396973"
              nverts="3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3"
              verts="0 1 2  0 3 1  4 0 2  5 4 2  6 5 2  7 3 0  7 0 4  8 6 2  9 4 5  9 7 4  10 8 2  11 9 5  11 5 6  12 13 3  12 14 13  12 3 7  15 10 2  16 11 6  16 6 8  17 7 9  17 12 7  18 15 2  19 8 10  19 16 8  20 9 11  20 17 9  21 18 2  22 19 10  22 10 15  23 11 16  23 20 11  24 21 2  25 14 12  25 12 17  26 22 15  26 15 18  27 23 16  27 16 19  28 24 2  29 25 17  29 17 20  30 26 18  30 18 21  31 27 19  31 19 22  32 28 2  33 20 23  33 29 20  34 30 21  34 21 24  35 36 14  35 37 36  35 14 25  38 31 22  38 22 26  39 32 2  40 23 27  40 33 23  41 24 28  41 34 24  42 25 29  42 35 25  43 26 30  43 38 26  44 39 2  45 40 27  45 27 31  46 28 32  46 41 28  47 42 29  47 29 33  48 30 34  48 43 30  49 44 2  50 31 38  50 45 31  51 32 39  51 46 32  52 33 40  52 47 33  53 48 34  53 34 41  54 35 42  54 37 35  55 49 2  56 38 43  56 50 38  57 51 39  57 39 44  58 40 45  58 52 40  59 41 46  59 53 41  60 42 47  60 54 42  61 55 2  62 56 43  62 43 48  63 44 49  63 57 44  64 45 50  64 58 45  65 46 51  65 59 46  66 60 47  66 47 52  67 61 2  68 62 48  68 48 53  69 70 37  69 71 70  69 37 54  72 63 49  72 49 55  73 64 50  73 50 56  74 65 51  74 51 57  75 52 58  75 66 52  76 67 2  77 53 59  77 68 53  78 54 60  78 69 54  79 72 55  79 55 61  80 73 56  80 56 62  81 74 57  81 57 63  82 58 64  82 75 58  83 76 2  84 59 65  84 77 59  85 78 60  85 60 66  86 79 61  86 61 67  87 80 62  87 62 68  88 63 72  88 81 63  89 64 73  89 82 64  90 83 2  91 84 65  91 65 74  92 66 75  92 85 66  93 67 76  93 86 67  94 68 77  94 87 68  95 71 69  95 69 78  96 88 72  96 72 79  97 73 80  97 89 73  98 90 2  99 74 81  99 91 74  100 75 82  100 92 75  101 76 83  101 93 76  102 94 77  102 77 84  103 95 78  103 78 85  104 96 79  104 79 86  105 80 87  105 97 80  106 2 1  106 1 3  106 98 2  107 81 88  107 99 81  108 82 89  108 100 82  109 101 83  109 83 90  110 102 84  110 84 91  111 103 85  111 85 92  112 104 86  112 86 93  113 87 94  113 105 87  114 115 71  114 116 115  114 71 95  117 107 88  117 88 96  118 108 89  118 89 97  119 90 98  119 109 90  120 110 91  120 91 99  121 92 100  121 111 92  122 112 93  122 93 101  123 94 102  123 113 94  124 95 103  124 114 95  125 96 104  125 117 96  126 97 105  126 118 97  127 106 3  127 98 106  127 119 98  128 120 99  128 99 107  129 100 108  129 121 100  130 101 109  130 122 101  131 123 102  131 102 110  132 103 111  132 124 103  133 125 104  133 104 112  134 105 113  134 126 105  135 128 107  135 107 117  136 129 108  136 108 118  137 109 119  137 130 109  138 131 110  138 110 120  139 111 121  139 132 111  140 133 112  140 112 122  141 134 113  141 113 123  142 116 114  142 114 124  143 135 117  143 117 125  144 136 118  144 118 126  145 137 119  145 119 127  146 138 120  146 120 128  147 139 121  147 121 129  148 122 130  148 140 122  149 141 123  149 123 131  150 124 132  150 142 124  151 143 125  151 125 133  152 126 134  152 144 126  153 3 13  153 13 14  153 145 127  153 127 3  154 128 135  154 146 128  155 147 129  155 129 136  156 130 137  156 148 130  157 131 138  157 149 131  158 150 132  158 132 139  159 133 140  159 151 133  160 152 134  160 134 141  161 162 116  161 163 162  161 116 142  164 135 143  164 154 135  165 155 136  165 136 144  166 156 137  166 137 145  167 157 138  167 138 146  168 139 147  168 158 139  169 140 148  169 159 140  170 141 149  170 160 141  171 163 161  171 142 150  171 161 142  172 164 143  172 143 151  173 144 152  173 165 144  174 166 145  174 153 14  174 145 153  175 167 146  175 146 154  176 168 147  176 147 155  177 169 148  177 148 156  178 170 149  178 149 157  179 171 150  179 150 158  179 163 171  180 172 151  180 151 159  181 173 152  181 152 160  182 175 154  182 154 164  183 176 155  183 155 165  184 177 156  184 156 166  185 157 167  185 178 157  186 163 179  186 158 168  186 179 158  187 180 159  187 159 169  188 181 160  188 160 170  189 182 164  189 164 172  190 183 165  190 165 173  191 166 174  191 184 166  192 167 175  192 185 167  193 168 176  193 186 168  193 163 186  194 169 177  194 187 169  195 170 178  195 188 170  196 172 180  196 189 172  197 190 173  197 173 181  198 14 36  198 36 37  198 174 14  198 191 174  199 192 175  199 175 182  200 176 183  200 163 193  200 193 176  201 194 177  201 177 184  202 178 185  202 195 178  203 180 187  203 196 180  204 181 188  204 197 181  205 182 189  205 199 182  206 200 183  206 183 190  206 163 200  207 201 184  207 184 191  208 202 185  208 185 192  209 203 187  209 187 194  210 204 188  210 188 195  211 205 189  211 189 196  212 163 206  212 206 190  212 190 197  213 191 198  213 207 191  213 198 37  214 192 199  214 208 192  215 209 194  215 194 201  216 195 202  216 210 195  217 196 203  217 211 196  218 197 204  218 212 197  218 163 212  219 199 205  219 214 199  220 201 207  220 215 201  221 216 202  221 202 208  222 203 209  222 217 203  223 163 218  223 204 210  223 218 204  224 219 205  224 205 211  225 207 213  225 220 207  226 208 214  226 221 208  227 209 215  227 222 209  228 210 216  228 163 223  228 223 210  229 211 217  229 224 211  230 37 70  230 70 71  230 213 37  230 225 213  231 214 219  231 226 214  232 215 220  232 227 215  233 216 221  233 163 228  233 228 216  234 229 217  234 217 222  235 219 224  235 231 219  236 220 225  236 232 220  237 233 221  237 221 226  237 163 233  238 234 222  238 222 227  239 235 224  239 224 229  240 236 225  240 230 71  240 225 230  241 163 237  241 237 226  241 226 231  242 227 232  242 238 227  243 239 229  243 229 234  244 163 241  244 241 231  244 231 235  245 232 236  245 242 232  246 234 238  246 243 234  247 163 244  247 244 235  247 235 239  248 245 236  248 236 240  249 246 238  249 238 242  250 239 243  250 163 247  250 247 239  251 71 115  251 240 71  251 115 116  251 248 240  252 242 245  252 249 242  253 163 250  253 243 246  253 250 243  254 252 245  254 245 248  255 246 249  255 163 253  255 253 246  256 251 116  256 248 251  256 254 248  257 163 255  257 249 252  257 255 249  258 252 254  258 257 252  258 163 257  259 254 256  259 163 258  259 258 254  260 116 162  260 162 163  260 256 116  260 163 259  260 259 256"/>
    </state>`

**Comment by howetuft** [comment] 2021-04-06 20:46
Hello,
Yes, really interesting, I'll have a look at it in a couple of days, but for now, I've updated Cycles to the last version and it seems broken (at least on my system)..! Looks like a evolution/regression in xml parsing, I must ask for help on Cycles forum; before that, I unfortunately cannot test anything...

**Comment by HaasNL2** [comment] 2021-04-06 20:49
I jsut updated main post XD

**Comment by justnope** [comment] 2021-04-19 21:51
I think this is linked to #11 

The problem is when to apply smoothing and when to apply sharp angles. One way to solve it is to use crease angles between planes. I'm not sure if this should go into the renderer exporter. Maybe there's a way to export the normals of vertices instead of planes during the export? The rendering engine of freecad already supports crease angles and whatnot, maybe it could also export normals per vertex instead of per plane?

**Comment by luzpaz** [comment] 2022-07-25 22:47
any progress here?

**Comment by howetuft** [comment] 2022-07-26 04:17
Unfortunately no. I may have an idea, but no time to implement it. I'm currently focused on textures, which is quite demanding...

**Comment by howetuft** [comment] 2023-02-21 21:19
All good things come to those who wait: eventually, this have been addressed, for all renderers! I close this issue.

**Closed by howetuft** 2023-02-21 21:19 UTC

**Comment by MisterMakerNL** [comment] 2023-02-21 21:31
You added this? 😯

**Comment by howetuft** [comment] 2023-02-21 21:41
Yes, there is now an option in the View, called "Autosmooth", with an angle parameter, and when you activate it - which is done by default - the mesh is smoothed at rendering, except for the edges where the crease angle is above the angle parameter.
Illustrations:

![image](https://user-images.githubusercontent.com/34142192/220464608-b437e594-6040-49aa-bcc2-aca7e738bc65.png)
![image](https://user-images.githubusercontent.com/34142192/220463764-b2ac8013-924e-4da8-b601-1c33b4770eee.png)
![image](https://user-images.githubusercontent.com/34142192/220464866-5d550211-e739-437b-8fee-b44d85f9d229.png)
